### PR TITLE
Poetry?

### PR DESCRIPTION
**Pull request by ToxicKidz**

### CODE REVIEW

**Comment by asleep-cult** [comment]
-1

**Comment by asleep-cult** [comment]
[[package]]name = "appdirs"version = "1.4.4"description = "A small Python module for determining appropriate platform-specific dirs, e.g. a \"user data dir\"."category = "dev"optional = falsepython-versions = "*"[[package]]name = "certifi"version = "2020.12.5"description = "Python package for providing Mozilla's CA Bundle."category = "main"optional = falsepython-versions = "*"[[package]]name = "cfgv"version = "3.3.0"description = "Validate configuration and produce human readable error messages."category = "dev"optional = falsepython-versions = "&gt;=3.6.1"[[package]]name = "distlib"version = "0.3.1"description = "Distribution utilities"category = "dev"optional = falsepython-versions = "*"[[package]]name = "filelock"version = "3.0.12"description = "A platform independent file lock."category = "dev"optional = falsepython-versions = "*"[[package]]name = "flake8"version = "3.9.2"description = "the modular source code checker: pep8 pyflakes and co"category = "dev"optional = falsepython-versions = "!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,&gt;=2.7"[package.dependencies]importlib-metadata = {version = "*", markers = "python_version &lt; \"3.8\""}mccabe = "&gt;=0.6.0,&lt;0.7.0"pycodestyle = "&gt;=2.7.0,&lt;2.8.0"pyflakes = "&gt;=2.3.0,&lt;2.4.0"[[package]]name = "h11"version = "0.12.0"description = "A pure-Python, bring-your-own-I/O implementation of HTTP/1.1"category = "main"optional = falsepython-versions = "&gt;=3.6"[[package]]name = "httpcore"version = "0.13.3"description = "A minimal low-level HTTP client."category = "main"optional = falsepython-versions = "&gt;=3.6"[package.dependencies]h11 = "&gt;=0.11,&lt;0.13"sniffio = "&gt;=1.0.0,&lt;2.0.0"[package.extras]http2 = ["h2 (&gt;=3,&lt;5)"][[package]]name = "httpx"version = "0.18.1"description = "The next generation HTTP client."category = "main"optional = falsepython-versions = "&gt;=3.6"[package.dependencies]certifi = "*"httpcore = "&gt;=0.13.0,&lt;0.14.0"rfc3986 = {version = "&gt;=1.3,&lt;2", extras = ["idna2008"]}sniffio = "*"[package.extras]brotli = ["brotlicffi (&gt;=1.0.0,&lt;2.0.0)"]http2 = ["h2 (&gt;=3.0.0,&lt;4.0.0)"][[package]]name = "identify"version = "2.2.4"description = "File identification library for Python"category = "dev"optional = falsepython-versions = "&gt;=3.6.1"[package.extras]license = ["editdistance-s"][[package]]name = "idna"version = "3.1"description = "Internationalized Domain Names in Applications (IDNA)"category = "main"optional = falsepython-versions = "&gt;=3.4"[[package]]name = "importlib-metadata"version = "4.0.1"description = "Read metadata from Python packages"category = "dev"optional = falsepython-versions = "&gt;=3.6"[package.dependencies]typing-extensions = {version = "&gt;=3.6.4", markers = "python_version &lt; \"3.8\""}zipp = "&gt;=0.5"[package.extras]docs = ["sphinx", "jaraco.packaging (&gt;=8.2)", "rst.linker (&gt;=1.9)"]testing = ["pytest (&gt;=4.6)", "pytest-checkdocs (&gt;=2.4)", "pytest-flake8", "pytest-cov", "pytest-enabler (&gt;=1.0.1)", "packaging", "pep517", "pyfakefs", "flufl.flake8", "pytest-black (&gt;=0.3.7)", "pytest-mypy", "importlib-resources (&gt;=1.3)"][[package]]name = "mccabe"version = "0.6.1"description = "McCabe checker, plugin for flake8"category = "dev"optional = falsepython-versions = "*"[[package]]name = "nodeenv"version = "1.6.0"description = "Node.js virtual environment builder"category = "dev"optional = falsepython-versions = "*"[[package]]name = "pre-commit"version = "2.12.1"description = "A framework for managing and maintaining multi-language pre-commit hooks."category = "dev"optional = falsepython-versions = "&gt;=3.6.1"[package.dependencies]cfgv = "&gt;=2.0.0"identify = "&gt;=1.0.0"importlib-metadata = {version = "*", markers = "python_version &lt; \"3.8\""}nodeenv = "&gt;=0.11.1"pyyaml = "&gt;=5.1"toml = "*"virtualenv = "&gt;=20.0.8"[[package]]name = "pycodestyle"version = "2.7.0"description = "Python style guide checker"category = "dev"optional = falsepython-versions = "&gt;=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*"[[package]]name = "pyflakes"version = "2.3.1"description = "passive checker of Python programs"category = "dev"optional = falsepython-versions = "&gt;=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*"[[package]]name = "pyyaml"version = "5.4.1"description = "YAML parser and emitter for Python"category = "dev"optional = falsepython-versions = "&gt;=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*"[[package]]name = "rfc3986"version = "1.5.0"description = "Validating URI References per RFC 3986"category = "main"optional = falsepython-versions = "*"[package.dependencies]idna = {version = "*", optional = true, markers = "extra == \"idna2008\""}[package.extras]idna2008 = ["idna"][[package]]name = "six"version = "1.16.0"description = "Python 2 and 3 compatibility utilities"category = "dev"optional = falsepython-versions = "&gt;=2.7, !=3.0.*, !=3.1.*, !=3.2.*"[[package]]name = "snakecord-emojis"version = "0.0.2"description = "All Discord emojis for snakecord"category = "main"optional = falsepython-versions = "*"[[package]]name = "sniffio"version = "1.2.0"description = "Sniff out which async library your code is running under"category = "main"optional = falsepython-versions = "&gt;=3.5"[[package]]name = "toml"version = "0.10.2"description = "Python Library for Tom's Obvious, Minimal Language"category = "dev"optional = falsepython-versions = "&gt;=2.6, !=3.0.*, !=3.1.*, !=3.2.*"[[package]]name = "typing-extensions"version = "3.10.0.0"description = "Backported and Experimental Type Hints for Python 3.5+"category = "dev"optional = falsepython-versions = "*"[[package]]name = "virtualenv"version = "20.4.6"description = "Virtual Python Environment builder"category = "dev"optional = falsepython-versions = "!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,&gt;=2.7"[package.dependencies]appdirs = "&gt;=1.4.3,&lt;2"distlib = "&gt;=0.3.1,&lt;1"filelock = "&gt;=3.0.0,&lt;4"importlib-metadata = {version = "&gt;=0.12", markers = "python_version &lt; \"3.8\""}six = "&gt;=1.9.0,&lt;2"[package.extras]docs = ["proselint (&gt;=0.10.2)", "sphinx (&gt;=3)", "sphinx-argparse (&gt;=0.2.5)", "sphinx-rtd-theme (&gt;=0.4.3)", "towncrier (&gt;=19.9.0rc1)"]testing = ["coverage (&gt;=4)", "coverage-enable-subprocess (&gt;=1)", "flaky (&gt;=3)", "pytest (&gt;=4)", "pytest-env (&gt;=0.6.2)", "pytest-freezegun (&gt;=0.4.1)", "pytest-mock (&gt;=2)", "pytest-randomly (&gt;=1)", "pytest-timeout (&gt;=1)", "packaging (&gt;=20.0)", "xonsh (&gt;=0.9.16)"][[package]]name = "wsaio"version = "0.0.4"description = "An event-driven WebSocket library for Python."category = "main"optional = falsepython-versions = "&gt;=3.7"[[package]]name = "zipp"version = "3.4.1"description = "Backport of pathlib-compatible object wrapper for zip files"category = "dev"optional = falsepython-versions = "&gt;=3.6"[package.extras]docs = ["sphinx", "jaraco.packaging (&gt;=8.2)", "rst.linker (&gt;=1.9)"]testing = ["pytest (&gt;=4.6)", "pytest-checkdocs (&gt;=1.2.3)", "pytest-flake8", "pytest-cov", "pytest-enabler", "jaraco.itertools", "func-timeout", "pytest-black (&gt;=0.3.7)", "pytest-mypy"][metadata]lock-version = "1.1"python-versions = "&gt;=3.7"content-hash = "da2d1ff3321b5ca3a9476c11831222c6d9860101fd107d58418119acfe827ef1"[metadata.files]appdirs = [    {file = "appdirs-1.4.4-py2.py3-none-any.whl", hash = "sha256:a841dacd6b99318a741b166adb07e19ee71a274450e68237b4650ca1055ab128"},    {file = "appdirs-1.4.4.tar.gz", hash = "sha256:7d5d0167b2b1ba821647616af46a749d1c653740dd0d2415100fe26e27afdf41"},]certifi = [    {file = "certifi-2020.12.5-py2.py3-none-any.whl", hash = "sha256:719a74fb9e33b9bd44cc7f3a8d94bc35e4049deebe19ba7d8e108280cfd59830"},    {file = "certifi-2020.12.5.tar.gz", hash = "sha256:1a4995114262bffbc2413b159f2a1a480c969de6e6eb13ee966d470af86af59c"},]cfgv = [    {file = "cfgv-3.3.0-py2.py3-none-any.whl", hash = "sha256:b449c9c6118fe8cca7fa5e00b9ec60ba08145d281d52164230a69211c5d597a1"},    {file = "cfgv-3.3.0.tar.gz", hash = "sha256:9e600479b3b99e8af981ecdfc80a0296104ee610cab48a5ae4ffd0b668650eb1"},]distlib = [    {file = "distlib-0.3.1-py2.py3-none-any.whl", hash = "sha256:8c09de2c67b3e7deef7184574fc060ab8a793e7adbb183d942c389c8b13c52fb"},    {file = "distlib-0.3.1.zip", hash = "sha256:edf6116872c863e1aa9d5bb7cb5e05a022c519a4594dc703843343a9ddd9bff1"},]filelock = [    {file = "filelock-3.0.12-py3-none-any.whl", hash = "sha256:929b7d63ec5b7d6b71b0fa5ac14e030b3f70b75747cef1b10da9b879fef15836"},    {file = "filelock-3.0.12.tar.gz", hash = "sha256:18d82244ee114f543149c66a6e0c14e9c4f8a1044b5cdaadd0f82159d6a6ff59"},]flake8 = [    {file = "flake8-3.9.2-py2.py3-none-any.whl", hash = "sha256:bf8fd333346d844f616e8d47905ef3a3384edae6b4e9beb0c5101e25e3110907"},    {file = "flake8-3.9.2.tar.gz", hash = "sha256:07528381786f2a6237b061f6e96610a4167b226cb926e2aa2b6b1d78057c576b"},]h11 = [    {file = "h11-0.12.0-py3-none-any.whl", hash = "sha256:36a3cb8c0a032f56e2da7084577878a035d3b61d104230d4bd49c0c6b555a9c6"},    {file = "h11-0.12.0.tar.gz", hash = "sha256:47222cb6067e4a307d535814917cd98fd0a57b6788ce715755fa2b6c28b56042"},]httpcore = [    {file = "httpcore-0.13.3-py3-none-any.whl", hash = "sha256:ff614f0ef875b9e5fe0bdd459b31ea0eea282ff12dc82add83d68b3811ee94ad"},    {file = "httpcore-0.13.3.tar.gz", hash = "sha256:5d674b57a11275904d4fd0819ca02f960c538e4472533620f322fc7db1ea0edc"},]httpx = [    {file = "httpx-0.18.1-py3-none-any.whl", hash = "sha256:ad2e3db847be736edc4b272c4d5788790a7e5789ef132fc6b5fef8aeb9e9f6e0"},    {file = "httpx-0.18.1.tar.gz", hash = "sha256:0a2651dd2b9d7662c70d12ada5c290abcf57373b9633515fe4baa9f62566086f"},]identify = [    {file = "identify-2.2.4-py2.py3-none-any.whl", hash = "sha256:ad9f3fa0c2316618dc4d840f627d474ab6de106392a4f00221820200f490f5a8"},    {file = "identify-2.2.4.tar.gz", hash = "sha256:9bcc312d4e2fa96c7abebcdfb1119563b511b5e3985ac52f60d9116277865b2e"},]idna = [    {file = "idna-3.1-py3-none-any.whl", hash = "sha256:5205d03e7bcbb919cc9c19885f9920d622ca52448306f2377daede5cf3faac16"},    {file = "idna-3.1.tar.gz", hash = "sha256:c5b02147e01ea9920e6b0a3f1f7bb833612d507592c837a6c49552768f4054e1"},]importlib-metadata = [    {file = "importlib_metadata-4.0.1-py3-none-any.whl", hash = "sha256:d7eb1dea6d6a6086f8be21784cc9e3bcfa55872b52309bc5fad53a8ea444465d"},    {file = "importlib_metadata-4.0.1.tar.gz", hash = "sha256:8c501196e49fb9df5df43833bdb1e4328f64847763ec8a50703148b73784d581"},]mccabe = [    {file = "mccabe-0.6.1-py2.py3-none-any.whl", hash = "sha256:ab8a6258860da4b6677da4bd2fe5dc2c659cff31b3ee4f7f5d64e79735b80d42"},    {file = "mccabe-0.6.1.tar.gz", hash = "sha256:dd8d182285a0fe56bace7f45b5e7d1a6ebcbf524e8f3bd87eb0f125271b8831f"},]nodeenv = [    {file = "nodeenv-1.6.0-py2.py3-none-any.whl", hash = "sha256:621e6b7076565ddcacd2db0294c0381e01fd28945ab36bcf00f41c5daf63bef7"},    {file = "nodeenv-1.6.0.tar.gz", hash = "sha256:3ef13ff90291ba2a4a7a4ff9a979b63ffdd00a464dbe04acf0ea6471517a4c2b"},]pre-commit = [    {file = "pre_commit-2.12.1-py2.py3-none-any.whl", hash = "sha256:70c5ec1f30406250b706eda35e868b87e3e4ba099af8787e3e8b4b01e84f4712"},    {file = "pre_commit-2.12.1.tar.gz", hash = "sha256:900d3c7e1bf4cf0374bb2893c24c23304952181405b4d88c9c40b72bda1bb8a9"},]pycodestyle = [    {file = "pycodestyle-2.7.0-py2.py3-none-any.whl", hash = "sha256:514f76d918fcc0b55c6680472f0a37970994e07bbb80725808c17089be302068"},    {file = "pycodestyle-2.7.0.tar.gz", hash = "sha256:c389c1d06bf7904078ca03399a4816f974a1d590090fecea0c63ec26ebaf1cef"},]pyflakes = [    {file = "pyflakes-2.3.1-py2.py3-none-any.whl", hash = "sha256:7893783d01b8a89811dd72d7dfd4d84ff098e5eed95cfa8905b22bbffe52efc3"},    {file = "pyflakes-2.3.1.tar.gz", hash = "sha256:f5bc8ecabc05bb9d291eb5203d6810b49040f6ff446a756326104746cc00c1db"},]pyyaml = [    {file = "PyYAML-5.4.1-cp27-cp27m-macosx_10_9_x86_64.whl", hash = "sha256:3b2b1824fe7112845700f815ff6a489360226a5609b96ec2190a45e62a9fc922"},    {file = "PyYAML-5.4.1-cp27-cp27m-win32.whl", hash = "sha256:129def1b7c1bf22faffd67b8f3724645203b79d8f4cc81f674654d9902cb4393"},    {file = "PyYAML-5.4.1-cp27-cp27m-win_amd64.whl", hash = "sha256:4465124ef1b18d9ace298060f4eccc64b0850899ac4ac53294547536533800c8"},    {file = "PyYAML-5.4.1-cp27-cp27mu-manylinux1_x86_64.whl", hash = "sha256:bb4191dfc9306777bc594117aee052446b3fa88737cd13b7188d0e7aa8162185"},    {file = "PyYAML-5.4.1-cp36-cp36m-macosx_10_9_x86_64.whl", hash = "sha256:6c78645d400265a062508ae399b60b8c167bf003db364ecb26dcab2bda048253"},    {file = "PyYAML-5.4.1-cp36-cp36m-manylinux1_x86_64.whl", hash = "sha256:4e0583d24c881e14342eaf4ec5fbc97f934b999a6828693a99157fde912540cc"},    {file = "PyYAML-5.4.1-cp36-cp36m-manylinux2014_aarch64.whl", hash = "sha256:72a01f726a9c7851ca9bfad6fd09ca4e090a023c00945ea05ba1638c09dc3347"},    {file = "PyYAML-5.4.1-cp36-cp36m-manylinux2014_s390x.whl", hash = "sha256:895f61ef02e8fed38159bb70f7e100e00f471eae2bc838cd0f4ebb21e28f8541"},    {file = "PyYAML-5.4.1-cp36-cp36m-win32.whl", hash = "sha256:3bd0e463264cf257d1ffd2e40223b197271046d09dadf73a0fe82b9c1fc385a5"},    {file = "PyYAML-5.4.1-cp36-cp36m-win_amd64.whl", hash = "sha256:e4fac90784481d221a8e4b1162afa7c47ed953be40d31ab4629ae917510051df"},    {file = "PyYAML-5.4.1-cp37-cp37m-macosx_10_9_x86_64.whl", hash = "sha256:5accb17103e43963b80e6f837831f38d314a0495500067cb25afab2e8d7a4018"},    {file = "PyYAML-5.4.1-cp37-cp37m-manylinux1_x86_64.whl", hash = "sha256:e1d4970ea66be07ae37a3c2e48b5ec63f7ba6804bdddfdbd3cfd954d25a82e63"},    {file = "PyYAML-5.4.1-cp37-cp37m-manylinux2014_aarch64.whl", hash = "sha256:cb333c16912324fd5f769fff6bc5de372e9e7a202247b48870bc251ed40239aa"},    {file = "PyYAML-5.4.1-cp37-cp37m-manylinux2014_s390x.whl", hash = "sha256:fe69978f3f768926cfa37b867e3843918e012cf83f680806599ddce33c2c68b0"},    {file = "PyYAML-5.4.1-cp37-cp37m-win32.whl", hash = "sha256:dd5de0646207f053eb0d6c74ae45ba98c3395a571a2891858e87df7c9b9bd51b"},    {file = "PyYAML-5.4.1-cp37-cp37m-win_amd64.whl", hash = "sha256:08682f6b72c722394747bddaf0aa62277e02557c0fd1c42cb853016a38f8dedf"},    {file = "PyYAML-5.4.1-cp38-cp38-macosx_10_9_x86_64.whl", hash = "sha256:d2d9808ea7b4af864f35ea216be506ecec180628aced0704e34aca0b040ffe46"},    {file = "PyYAML-5.4.1-cp38-cp38-manylinux1_x86_64.whl", hash = "sha256:8c1be557ee92a20f184922c7b6424e8ab6691788e6d86137c5d93c1a6ec1b8fb"},    {file = "PyYAML-5.4.1-cp38-cp38-manylinux2014_aarch64.whl", hash = "sha256:fd7f6999a8070df521b6384004ef42833b9bd62cfee11a09bda1079b4b704247"},    {file = "PyYAML-5.4.1-cp38-cp38-manylinux2014_s390x.whl", hash = "sha256:bfb51918d4ff3d77c1c856a9699f8492c612cde32fd3bcd344af9be34999bfdc"},    {file = "PyYAML-5.4.1-cp38-cp38-win32.whl", hash = "sha256:fa5ae20527d8e831e8230cbffd9f8fe952815b2b7dae6ffec25318803a7528fc"},    {file = "PyYAML-5.4.1-cp38-cp38-win_amd64.whl", hash = "sha256:0f5f5786c0e09baddcd8b4b45f20a7b5d61a7e7e99846e3c799b05c7c53fa696"},    {file = "PyYAML-5.4.1-cp39-cp39-macosx_10_9_x86_64.whl", hash = "sha256:294db365efa064d00b8d1ef65d8ea2c3426ac366c0c4368d930bf1c5fb497f77"},    {file = "PyYAML-5.4.1-cp39-cp39-manylinux1_x86_64.whl", hash = "sha256:74c1485f7707cf707a7aef42ef6322b8f97921bd89be2ab6317fd782c2d53183"},    {file = "PyYAML-5.4.1-cp39-cp39-manylinux2014_aarch64.whl", hash = "sha256:d483ad4e639292c90170eb6f7783ad19490e7a8defb3e46f97dfe4bacae89122"},    {file = "PyYAML-5.4.1-cp39-cp39-manylinux2014_s390x.whl", hash = "sha256:fdc842473cd33f45ff6bce46aea678a54e3d21f1b61a7750ce3c498eedfe25d6"},    {file = "PyYAML-5.4.1-cp39-cp39-win32.whl", hash = "sha256:49d4cdd9065b9b6e206d0595fee27a96b5dd22618e7520c33204a4a3239d5b10"},    {file = "PyYAML-5.4.1-cp39-cp39-win_amd64.whl", hash = "sha256:c20cfa2d49991c8b4147af39859b167664f2ad4561704ee74c1de03318e898db"},    {file = "PyYAML-5.4.1.tar.gz", hash = "sha256:607774cbba28732bfa802b54baa7484215f530991055bb562efbed5b2f20a45e"},]rfc3986 = [    {file = "rfc3986-1.5.0-py2.py3-none-any.whl", hash = "sha256:a86d6e1f5b1dc238b218b012df0aa79409667bb209e58da56d0b94704e712a97"},    {file = "rfc3986-1.5.0.tar.gz", hash = "sha256:270aaf10d87d0d4e095063c65bf3ddbc6ee3d0b226328ce21e036f946e421835"},]six = [    {file = "six-1.16.0-py2.py3-none-any.whl", hash = "sha256:8abb2f1d86890a2dfb989f9a77cfcfd3e47c2a354b01111771326f8aa26e0254"},    {file = "six-1.16.0.tar.gz", hash = "sha256:1e61c37477a1626458e36f7b1d82aa5c9b094fa4802892072e49de9c60c4c926"},]snakecord-emojis = [    {file = "snakecord-emojis-0.0.2.tar.gz", hash = "sha256:7a83e1fcd3baebb31458a56ea5280cea9257f77a5f44c998b43fea7891892e37"},    {file = "snakecord_emojis-0.0.2-py3-none-any.whl", hash = "sha256:a18e8c6e04d16a10bd449b2be2093ef07d3962f965d8c11da0455e9b0fe6f175"},]sniffio = [    {file = "sniffio-1.2.0-py3-none-any.whl", hash = "sha256:471b71698eac1c2112a40ce2752bb2f4a4814c22a54a3eed3676bc0f5ca9f663"},    {file = "sniffio-1.2.0.tar.gz", hash = "sha256:c4666eecec1d3f50960c6bdf61ab7bc350648da6c126e3cf6898d8cd4ddcd3de"},]toml = [    {file = "toml-0.10.2-py2.py3-none-any.whl", hash = "sha256:806143ae5bfb6a3c6e736a764057db0e6a0e05e338b5630894a5f779cabb4f9b"},    {file = "toml-0.10.2.tar.gz", hash = "sha256:b3bda1d108d5dd99f4a20d24d9c348e91c4db7ab1b749200bded2f839ccbe68f"},]typing-extensions = [    {file = "typing_extensions-3.10.0.0-py2-none-any.whl", hash = "sha256:0ac0f89795dd19de6b97debb0c6af1c70987fd80a2d62d1958f7e56fcc31b497"},    {file = "typing_extensions-3.10.0.0-py3-none-any.whl", hash = "sha256:779383f6086d90c99ae41cf0ff39aac8a7937a9283ce0a414e5dd782f4c94a84"},    {file = "typing_extensions-3.10.0.0.tar.gz", hash = "sha256:50b6f157849174217d0656f99dc82fe932884fb250826c18350e159ec6cdf342"},]virtualenv = [    {file = "virtualenv-20.4.6-py2.py3-none-any.whl", hash = "sha256:307a555cf21e1550885c82120eccaf5acedf42978fd362d32ba8410f9593f543"},    {file = "virtualenv-20.4.6.tar.gz", hash = "sha256:72cf267afc04bf9c86ec932329b7e94db6a0331ae9847576daaa7ca3c86b29a4"},]wsaio = [    {file = "wsaio-0.0.4-py3-none-any.whl", hash = "sha256:de3783f6bce20f6ad2965ea4e40b39de485ae45d39421f8917b162e2e75f2ebb"},    {file = "wsaio-0.0.4.tar.gz", hash = "sha256:341e19db5bfdf5ac88c673087f1d725798ca98ac0794ed646152d0c6168d3192"},]zipp = [    {file = "zipp-3.4.1-py3-none-any.whl", hash = "sha256:51cb66cc54621609dd593d1787f286ee42a5c0adbb4b29abea5a63edc3e03098"},    {file = "zipp-3.4.1.tar.gz", hash = "sha256:3607921face881ba3e026887d8150cca609d517579abe052ac81fc5aeffdbd76"},]

**Comment by ToxicKidz** [comment]
Merging this should help with broken pre commit

**Comment by asleep-cult** [comment]
how to contribute
```py
pip uninstall poetry
pip install pre-commit
pre-commit install
```

**Comment by ToxicKidz** [comment]
running pre-commit would fail though

**Comment by asleep-cult** [comment]
no

**Pull request closed without merging**
