### PR TITLE
Adds typing to snekcord instead of stubs

### PR DESCRIPTION
**Pull request by ToxicKidz**
The stubs didn't even work, and there is no point of trying to maintain them. ~~merge-typing more like merge-conflicts XDD~~

### CODE REVIEW

**Review by anand2312 — APPROVED** [review]
best PR ever

**Comment by ToxicKidz** [comment]
✅ LGTM

**Comment by asleep-cult** [comment]
Hi my name is asleep-cult and I would like to revert this commit. :-1:

**Comment by ToxicKidz** [comment]
sorry u feel that way

**Comment by asleep-cult** [comment]
sorry you don't feel that way :smiling_imp:

**Pull request merged**
